# Generated by Django 2.1.4 on 2018-12-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycompare', '0003_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteparameter',
            old_name='source_amount',
            new_name='input_amount',
        ),
        migrations.RenameField(
            model_name='quoteparameter',
            old_name='source_currency',
            new_name='input_from',
        ),
        migrations.RenameField(
            model_name='quoteparameter',
            old_name='target_currency',
            new_name='input_to',
        ),
        migrations.AddField(
            model_name='quoteparameter',
            name='response_amount',
            field=models.CharField(default='targetAmount', max_length=50),
            preserve_default=False,
        ),
    ]
