# Generated by Django 2.1.4 on 2018-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycompare', '0004_auto_20181227_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteparameter',
            name='response_target_currency',
            field=models.CharField(default='target', max_length=50),
            preserve_default=False,
        ),
    ]
