# Generated by Django 2.1.4 on 2018-12-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_api', models.CharField(max_length=200)),
                ('exchange_rate_api', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(max_length=50)),
                ('target_currency', models.CharField(max_length=50)),
                ('source_amount', models.CharField(max_length=50)),
                ('remaining_attributes', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='quoteparameter',
            name='vendor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycompare.Vendor'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='vendor_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moneycompare.Vendor'),
        ),
    ]
